#include "idt.h"
#include "io.h"
#include <kprintf.h>

#define ISR_NAME(index) isr_##index

#define IDT_INSTALL_CLI(index) ({ \
    extern void ISR_NAME(index)(void); \
    idt_entry_init(index, (uint64_t)ISR_NAME(index), 0x8E); \
})

#define IDT_INSTALL_STI(index) ({ \
    extern void ISR_NAME(index)(void); \
    idt_entry_init(index, (uint64_t)ISR_NAME(index), 0x8F); \
})

static idt_register idt_reg;

// TODO: Add max size into a macro
__attribute__((aligned(16)))
static idt_entry idt_entries[256];

/**
 * @brief Initialize a single IDT entry
 * 
 * @param i 
 * @param offset 
 * @param selector 
 * @param flags 
 */
void idt_entry_init(unsigned int i, uint64_t offset, uint8_t flags) {
    idt_entries[i].low_offset   = (uint64_t)offset & 0xFFFF;
    idt_entries[i].selector     = 0x08;                                     // Kernel Code Segment
    idt_entries[i].ist          = 0;
    idt_entries[i].flags        = flags;
    idt_entries[i].mid_offset   = ((uint64_t)offset >> 16) & 0xFFFF;
    idt_entries[i].high_offset  = ((uint64_t)offset >> 32) & 0xFFFFFFFF;
    idt_entries[i].zero         = 0;
}

// void IRQ_set_mask(unsigned char IRQline) {
//     uint16_t port;
//     uint8_t value;
 
//     if(IRQline < 8) {
//         port = PIC1_DATA;
//     } else {
//         port = PIC2_DATA;
//         IRQline -= 8;
//     }
//     value = inb(port) | (1 << IRQline);
//     outb(port, value);        
// }
 
// void IRQ_clear_mask(unsigned char IRQline) {
//     uint16_t port;
//     uint8_t value;
 
//     if(IRQline < 8) {
//         port = PIC1_DATA;
//     } else {
//         port = PIC2_DATA;
//         IRQline -= 8;
//     }
//     value = inb(port) & ~(1 << IRQline);
//     outb(port, value);        
// }

void idt_init(void) {
    // Init the IDT register
    idt_reg.limit = sizeof(idt_entry) * 256 - 1;
    idt_reg.base = (uintptr_t)&idt_entries[0];
    
    // CPU interrupts to signal exceptions and faults.
    IDT_INSTALL_CLI(0);
    IDT_INSTALL_CLI(1);
    IDT_INSTALL_CLI(2);
    IDT_INSTALL_CLI(3);
    IDT_INSTALL_CLI(4);
    IDT_INSTALL_CLI(5);
    IDT_INSTALL_CLI(6);
    IDT_INSTALL_CLI(7);
    IDT_INSTALL_CLI(8);
    IDT_INSTALL_CLI(9);
    IDT_INSTALL_CLI(10);
    IDT_INSTALL_CLI(11);
    IDT_INSTALL_CLI(12);
    IDT_INSTALL_CLI(13);
    IDT_INSTALL_CLI(14);
    IDT_INSTALL_CLI(15);
    IDT_INSTALL_CLI(16);
    IDT_INSTALL_CLI(17);
    IDT_INSTALL_CLI(18);
    IDT_INSTALL_CLI(19);
    IDT_INSTALL_CLI(20);
    IDT_INSTALL_CLI(21);
    IDT_INSTALL_CLI(22);
    IDT_INSTALL_CLI(23);
    IDT_INSTALL_CLI(24);
    IDT_INSTALL_CLI(25);
    IDT_INSTALL_CLI(26);
    IDT_INSTALL_CLI(27);
    IDT_INSTALL_CLI(28);
    IDT_INSTALL_CLI(29);
    IDT_INSTALL_CLI(30);
    IDT_INSTALL_CLI(31);

    // Devices interrupt requests (IRQs)
    IDT_INSTALL_STI(32);
    IDT_INSTALL_STI(33);
    IDT_INSTALL_STI(34);
    IDT_INSTALL_STI(35);
    IDT_INSTALL_STI(36);
    IDT_INSTALL_STI(37);
    IDT_INSTALL_STI(38);
    IDT_INSTALL_STI(39);
    IDT_INSTALL_STI(40);
    IDT_INSTALL_STI(41);
    IDT_INSTALL_STI(42);
    IDT_INSTALL_STI(43);
    IDT_INSTALL_STI(44);
    IDT_INSTALL_STI(45);
    IDT_INSTALL_STI(46);
    IDT_INSTALL_STI(47);

    IDT_INSTALL_STI(48);
	IDT_INSTALL_STI(49);
	IDT_INSTALL_STI(50);
	IDT_INSTALL_STI(51);
	IDT_INSTALL_STI(52);
	IDT_INSTALL_STI(53);
	IDT_INSTALL_STI(54);
	IDT_INSTALL_STI(55);
	IDT_INSTALL_STI(56);
	IDT_INSTALL_STI(57);
	IDT_INSTALL_STI(58);
	IDT_INSTALL_STI(59);
	IDT_INSTALL_STI(60);
	IDT_INSTALL_STI(61);
	IDT_INSTALL_STI(62);
	IDT_INSTALL_STI(63);
	IDT_INSTALL_STI(64);
	IDT_INSTALL_STI(65);
	IDT_INSTALL_STI(66);
	IDT_INSTALL_STI(67);
	IDT_INSTALL_STI(68);
	IDT_INSTALL_STI(69);
	IDT_INSTALL_STI(70);
	IDT_INSTALL_STI(71);
	IDT_INSTALL_STI(72);
	IDT_INSTALL_STI(73);
	IDT_INSTALL_STI(74);
	IDT_INSTALL_STI(75);
	IDT_INSTALL_STI(76);
	IDT_INSTALL_STI(77);
	IDT_INSTALL_STI(78);
	IDT_INSTALL_STI(79);
	IDT_INSTALL_STI(80);
	IDT_INSTALL_STI(81);
	IDT_INSTALL_STI(82);
	IDT_INSTALL_STI(83);
	IDT_INSTALL_STI(84);
	IDT_INSTALL_STI(85);
	IDT_INSTALL_STI(86);
	IDT_INSTALL_STI(87);
	IDT_INSTALL_STI(88);
	IDT_INSTALL_STI(89);
	IDT_INSTALL_STI(90);
	IDT_INSTALL_STI(91);
	IDT_INSTALL_STI(92);
	IDT_INSTALL_STI(93);
	IDT_INSTALL_STI(94);
	IDT_INSTALL_STI(95);
	IDT_INSTALL_STI(96);
	IDT_INSTALL_STI(97);
	IDT_INSTALL_STI(98);
	IDT_INSTALL_STI(99);
	IDT_INSTALL_STI(100);
	IDT_INSTALL_STI(101);
	IDT_INSTALL_STI(102);
	IDT_INSTALL_STI(103);
	IDT_INSTALL_STI(104);
	IDT_INSTALL_STI(105);
	IDT_INSTALL_STI(106);
	IDT_INSTALL_STI(107);
	IDT_INSTALL_STI(108);
	IDT_INSTALL_STI(109);
	IDT_INSTALL_STI(110);
	IDT_INSTALL_STI(111);
	IDT_INSTALL_STI(112);
	IDT_INSTALL_STI(113);
	IDT_INSTALL_STI(114);
	IDT_INSTALL_STI(115);
	IDT_INSTALL_STI(116);
	IDT_INSTALL_STI(117);
	IDT_INSTALL_STI(118);
	IDT_INSTALL_STI(119);
	IDT_INSTALL_STI(120);
	IDT_INSTALL_STI(121);
	IDT_INSTALL_STI(122);
	IDT_INSTALL_STI(123);
	IDT_INSTALL_STI(124);
	IDT_INSTALL_STI(125);
	IDT_INSTALL_STI(126);
	IDT_INSTALL_STI(127);
	IDT_INSTALL_STI(128);
	IDT_INSTALL_STI(129);
	IDT_INSTALL_STI(130);
	IDT_INSTALL_STI(131);
	IDT_INSTALL_STI(132);
	IDT_INSTALL_STI(133);
	IDT_INSTALL_STI(134);
	IDT_INSTALL_STI(135);
	IDT_INSTALL_STI(136);
	IDT_INSTALL_STI(137);
	IDT_INSTALL_STI(138);
	IDT_INSTALL_STI(139);
	IDT_INSTALL_STI(140);
	IDT_INSTALL_STI(141);
	IDT_INSTALL_STI(142);
	IDT_INSTALL_STI(143);
	IDT_INSTALL_STI(144);
	IDT_INSTALL_STI(145);
	IDT_INSTALL_STI(146);
	IDT_INSTALL_STI(147);
	IDT_INSTALL_STI(148);
	IDT_INSTALL_STI(149);
	IDT_INSTALL_STI(150);
	IDT_INSTALL_STI(151);
	IDT_INSTALL_STI(152);
	IDT_INSTALL_STI(153);
	IDT_INSTALL_STI(154);
	IDT_INSTALL_STI(155);
	IDT_INSTALL_STI(156);
	IDT_INSTALL_STI(157);
	IDT_INSTALL_STI(158);
	IDT_INSTALL_STI(159);
	IDT_INSTALL_STI(160);
	IDT_INSTALL_STI(161);
	IDT_INSTALL_STI(162);
	IDT_INSTALL_STI(163);
	IDT_INSTALL_STI(164);
	IDT_INSTALL_STI(165);
	IDT_INSTALL_STI(166);
	IDT_INSTALL_STI(167);
	IDT_INSTALL_STI(168);
	IDT_INSTALL_STI(169);
	IDT_INSTALL_STI(170);
	IDT_INSTALL_STI(171);
	IDT_INSTALL_STI(172);
	IDT_INSTALL_STI(173);
	IDT_INSTALL_STI(174);
	IDT_INSTALL_STI(175);
	IDT_INSTALL_STI(176);
	IDT_INSTALL_STI(177);
	IDT_INSTALL_STI(178);
	IDT_INSTALL_STI(179);
	IDT_INSTALL_STI(180);
	IDT_INSTALL_STI(181);
	IDT_INSTALL_STI(182);
	IDT_INSTALL_STI(183);
	IDT_INSTALL_STI(184);
	IDT_INSTALL_STI(185);
	IDT_INSTALL_STI(186);
	IDT_INSTALL_STI(187);
	IDT_INSTALL_STI(188);
	IDT_INSTALL_STI(189);
	IDT_INSTALL_STI(190);
	IDT_INSTALL_STI(191);
	IDT_INSTALL_STI(192);
	IDT_INSTALL_STI(193);
	IDT_INSTALL_STI(194);
	IDT_INSTALL_STI(195);
	IDT_INSTALL_STI(196);
	IDT_INSTALL_STI(197);
	IDT_INSTALL_STI(198);
	IDT_INSTALL_STI(199);
	IDT_INSTALL_STI(200);
	IDT_INSTALL_STI(201);
	IDT_INSTALL_STI(202);
	IDT_INSTALL_STI(203);
	IDT_INSTALL_STI(204);
	IDT_INSTALL_STI(205);
	IDT_INSTALL_STI(206);
	IDT_INSTALL_STI(207);
	IDT_INSTALL_STI(208);
	IDT_INSTALL_STI(209);
	IDT_INSTALL_STI(210);
	IDT_INSTALL_STI(211);
	IDT_INSTALL_STI(212);
	IDT_INSTALL_STI(213);
	IDT_INSTALL_STI(214);
	IDT_INSTALL_STI(215);
	IDT_INSTALL_STI(216);
	IDT_INSTALL_STI(217);
	IDT_INSTALL_STI(218);
	IDT_INSTALL_STI(219);
	IDT_INSTALL_STI(220);
	IDT_INSTALL_STI(221);
	IDT_INSTALL_STI(222);
	IDT_INSTALL_STI(223);
	IDT_INSTALL_STI(224);
	IDT_INSTALL_STI(225);
	IDT_INSTALL_STI(226);
	IDT_INSTALL_STI(227);
	IDT_INSTALL_STI(228);
	IDT_INSTALL_STI(229);
	IDT_INSTALL_STI(230);
	IDT_INSTALL_STI(231);
	IDT_INSTALL_STI(232);
	IDT_INSTALL_STI(233);
	IDT_INSTALL_STI(234);
	IDT_INSTALL_STI(235);
	IDT_INSTALL_STI(236);
	IDT_INSTALL_STI(237);
	IDT_INSTALL_STI(238);
	IDT_INSTALL_STI(239);
	IDT_INSTALL_STI(240);
	IDT_INSTALL_STI(241);
	IDT_INSTALL_STI(242);
	IDT_INSTALL_STI(243);
	IDT_INSTALL_STI(244);
	IDT_INSTALL_STI(245);
	IDT_INSTALL_STI(246);
	IDT_INSTALL_STI(247);
	IDT_INSTALL_STI(248);
	IDT_INSTALL_STI(249);
	IDT_INSTALL_STI(250);
	IDT_INSTALL_STI(251);
	IDT_INSTALL_STI(252);
	IDT_INSTALL_STI(253);
	IDT_INSTALL_STI(254);
	IDT_INSTALL_STI(255);
    
    /* Software interrupt (used by syscalls) */
    // TODO: Add to 128 syscall
}

/**
 * Loads IDT structure and enable interrupts
*/
void idt_load() {
    __asm__ __volatile__("lidt %0": : "m"(idt_reg));
    __asm__ __volatile__("sti");
}